kivy/kivy-designer

README.md

Edited README file for readability and misspellings. Added missing links for prerequisites.

Edited README file for readability

---

designer/uix/kv_lang_area.py

Simple Fix
closes #20 
Kv area
Property panel
UI

Fixed issue #20

---

Makefile
designer/add_file.py
designer/app.py
designer/common.py
designer/designer_content.py
designer/designer_settings.py
designer/eventviewer.py
designer/helper_functions.py
designer/new_dialog.py
designer/nodetree.py
designer/playground.py
designer/proj_watcher.py
designer/project_loader.py
designer/recent_manager.py
designer/statusbar.py
designer/toolbox.py
designer/tree.py
designer/uix/contextual.py
designer/uix/designer_sandbox.py
designer/uix/info_bubble.py
designer/uix/kivy_console.py
designer/uix/kv_lang_area.py
designer/uix/playground_size_selector.py
designer/uix/py_console.py
tools/pep8checker/pep8.py
tools/pep8checker/pep8kivy.py

I just rebased @gopar PR on master, updated pep8checker with kivy master and added tests to makefile
If this PR is fine, can close #72 
This PR will help me with #77

Pep8 from gopar rebased on master + tools/pep8checker updated

---

designer/uix/kivy_console.py

Fixes incorrect hostname on Windows, and incorrect username on OS X (as well as incorrect username on Linux, if you happened to run KD with sudo). Also caches hostname and username, which should not be changing while using the console.

fix console prompt

---

config.ini
designer/add_file.py
designer/app.py
designer/designer.kv
designer/designer_content.py
designer/designer_settings.py
designer/help_dialog.py
designer/helper_functions.py
designer/input_dialog.py
designer/project_loader.py
designer/project_settings.py
designer/recent_manager.py
designer/settings/buildozer_settings.json
designer/settings/hanga_settings.json
designer/statusbar.py
designer/uix/actioncheckbutton.py
designer/uix/contextual.py
designer/uix/designer_action_items.py

* [add view -> fullscreen](https://github.com/aron-bordin/kivy-designer/issues/50)
* [Save View settings](https://github.com/aron-bordin/kivy-designer/issues/44)
* [Close project button](https://github.com/aron-bordin/kivy-designer/issues/43)
* [File -> new File](https://github.com/aron-bordin/kivy-designer/issues/94)
* [New menu](https://github.com/aron-bordin/kivy-designer/issues/91)
* [small UI -> change the menu arrow position depending the parent position](https://github.com/aron-bordin/kivy-designer/issues/95)
* [Recent files not showing useful information](https://github.com/aron-bordin/kivy-designer/issues/2)
* [Remove some buttons on Start page](https://github.com/aron-bordin/kivy-designer/issues/1)
* [Project ­> Add File is not …

PR1 - New menu

---

designer/app.py
designer/uix/bug_reporter.py
main.py

As long as Kivy Designer is an IDE under development, would be great to alert to users about our bugs and mainly to get a feedback from them. So I created a Bug reporter, it's something basic, but I believe that this feature can help us to find more bugs. 
The entire app is running in a try catch, is some exception occurs, this window will be visible, with the possibility to copy the copy the traceback to the clipboard or to open a new issue on Github. 
to test it, you can on menu file, click and hold on recent files. When you release the button, KD will crash.
Issues:
https://github.com/aron-bordin/kivy-designer/issues/79

bug reporter

---

designer/app.py
designer/buildozer_spec_editor.py
designer/designer.kv
designer/designer_content.py
designer/settings/buildozer_spec_android.json
designer/settings/buildozer_spec_app.json
designer/settings/buildozer_spec_buildozer.json
designer/settings/buildozer_spec_ios.json
designer/start_page.py
designer/uix/settings.py

Spec editor ok.
[Buildozer configurator](https://github.com/aron-bordin/kivy-designer/issues/32)
[Kivy settings -> list item](https://github.com/aron-bordin/kivy-designer/issues/102)
Screenshots:
App screen:
Available menus:
raw spec editor:
raw spec editor checks if there is any error on .spec:
List with default values(Android permissions, for example):

Buildozer spec editor

---

config.ini
designer/app.py
designer/designer.kv
designer/designer_settings.py
designer/settings/designer_settings.json
designer/uix/completion_bubble.py
designer/uix/designer_code_input.py
designer/uix/kv_lang_area.py
designer/uix/py_code_input.py
designer/uix/settings.py
requirements.txt

requires: https://github.com/kivy/kivy-designer/pull/93
* Added Python autocompletion
* [Jedi integration](http://jedi.jedidjah.ch/)
* Line numbers on PyCodeInput and KvLangArea
* Pygments theme support to DesignerCodeInput(both PyCodeInput and KvLangArea)
* Theme selection:
* Line number:
* Autocompletions:

Improv pycodeinput

---

designer/designer.kv
designer/designer_content.py

Auto size
Custom styles
(The custom styles is not yet implemented! It'll be used later to show more info about the visible widget. text edited/problem with source code/file not tracked by git/etc)

closable tabs

---

designer/uix/py_console.py

Using shell as a ObjectProperty instead of a simple python var

sh as ObjectProperty

---

designer/designer.kv
designer/uix/actioncheckbutton.py
designer/uix/designer_action_items.py

Added description to actionbuttons. Will be used to display shortcuts

Action item desc

---

designer/settings/buildozer_spec_app.json
designer/uix/settings.py

Added some usual python modules to buildozer gui editor. (I used this list: https://github.com/kivy/python-for-android/tree/master/recipes) is it ok?
And garden modules

Usual python modules/garden repos in buildozer spec editor

---

designer/uix/kivy_console.py

Some bugs
* [execute a list of commands on Kivy Console](https://github.com/aron-bordin/kivy-designer/issues/96)
* [tab autocomplete not working on kivy_console](https://github.com/aron-bordin/kivy-designer/issues/55)
* [kivy console is always listening the keyboard](https://github.com/aron-bordin/kivy-designer/issues/56)
* [cannot clear kivy console](https://github.com/aron-bordin/kivy-designer/issues/58)
* [cannot clear kivy console](https://github.com/aron-bordin/kivy-designer/issues/58)
* [user can delete PS1 on console input](https://github.com/aron-bordin/kivy-designer/issues/59)
* [tab commands not working on console](https://github.com/aron-bordin/kivy-designer/issues/60)
* [hard-coded cd](https://github.com/aron-bordin/kivy-designer/issues/75)

kivy console bug fixes and improv

---

designer/app.py
designer/designer.kv
designer/uix/designer_code_input.py

editcontview fixes. It was not working with PyCodeInput.

Fixes editcontview

---

designer/app.py

Help file with full path
Fixes https://github.com/kivy/kivy-designer/issues/107

fix help file path

---

designer/app.py
designer/designer_content.py
designer/playground.py
designer/proj_watcher.py

Closes the tabs from a project before opening a another proj and ignores .buildozer folder

small fixes

---

designer/app.py
designer/profiler.py
designer/statusbar.py
new_templates/default.spec

Tool to manage customs Builders(now with Desktop and Buildozer working, Hanga in the future; and super easy to extend).
Interface to run/build/clean/stop/rebuild project

KD Builder

---

designer/designer_settings.py

removed old settings panel and just removed non used imports

[KD Settings|Fixes] import optimized. removed old setting panel

---

config.ini

fix default theme name

---

designer/uix/bug_reporter.py

Some reported bugs has no information about installed packages or OS version.
Adds to Bug Reporter the KD requirements installed version, Python version and running OS

bug reporter with env info

---

designer/app.py
designer/confirmation_dialog.py
designer/designer.kv
designer/uix/bug_reporter.py

As I was going through the code I saw couple of bugs, so decided to fix them and made little changes. 
* Added a new confirmation dialog box for the Quit button. (see picture) 
* Added 2 new object properties that might also be helpful in future. 
* Added a new method for "quit" action button to handle.
* And also there was a bug related to save as.

Fixing  save as and quit and adding some new methods 

---

designer/designer.kv

add a scrollview to project tree

fix #155 - add scrollview to project tree

---

designer/app.py
designer/designer.kv

Removed duplicate about ui, added link to KD docs

help fixes

---

config.ini
designer/app.py
designer/designer.kv
designer/recent_manager.py
designer/start_page.py

* Update the start page and recent dialog UI
* added links to kivy docs and kd docs

Start page

---

config.ini
designer/app.py
designer/settings/designer_settings.json
designer/uix/kivy_console.py
tests/test_uix.py

small modifications to kivy console.
* now it's working with Python 3. 
* performance problem fixed (the same command output was being processed and displayed 3 times. Slow with long outputs ;/)
* added an option on Kivy Settings to set the maximum number of lines on kivy console
* added pygments ShellSessionLexer to command output

fixes in kivy console - py3 comp

---

designer/uix/bug_reporter.py

I've seen a lot of bug reports coming from Bug Reporter with incomplete traceback. This is caused if the browser doesn't support long urls.
This pr adds a warning to explain it to the user. (The popup is displayed when the user press the "Report Bug" button"

add warning to bug reporter

---

designer/app.py
designer/designer_tools.py
designer/helper_functions.py
designer/new_dialog.py
designer/profile_settings.py
designer/profiler.py
designer/recent_manager.py
designer/start_page.py
designer/uix/bug_reporter.py
designer/uix/kivy_console.py
main.py
tests/test_apps.py

We have faced a lot of bugs related with encoding on Windows. This pr provides some checks to ensure that KD uses the same encoding that the OS to read/write files, and mainly paths.

windows encoding fixes

---

designer/new_dialog.py

Now user can navigate in the new project dialog box and open the projects by keyboard.
Press **'up'**       -> to go up
Press **'down'**  -> to go down
Press **'enter'**  -> to open the project

navigate via keyboard

---

designer/uix/bug_reporter.py

fix reporter warning bug

---

designer/app.py
designer/components/designer_content.py
designer/components/event_viewer.py
designer/components/kv_lang_area.py
designer/components/playground.py
designer/components/playground_size_selector.py
designer/components/property_viewer.py
designer/components/start_page.py
designer/components/statusbar.py
designer/components/toolbox.py
designer/components/ui_creator.py
designer/components/widgets_tree.py
designer/core/project_manager.py
designer/uix/contextual.py
designer/uix/input_dialog.py
setup.py

This prs adds the KD's setup.py, that allows the user to install KD in the machine and easily execute it using the command "kivydesigner"

add setup.py

---

designer/app.py
designer/components/dialogs/add_file.py
designer/core/builder.py
designer/core/project_manager.py

Remove unecessary project modified warning

---

designer/data/new_templates/default.spec
designer/data/settings/buildozer_spec_android.json
designer/data/settings/buildozer_spec_app.json
designer/data/settings/buildozer_spec_buildozer.json
designer/data/settings/buildozer_spec_ios.json

Use new .spec file for buildozer

---

designer/app.py

Update _perform_new_file method to use instance of input_dialog
Fixes #292

Add File Patch

---

designer/app.py
designer/components/dialogs/new_project.py
designer/data/new_templates/default.spec
designer/designer.kv

Closes #260 
Also, update default.spec to newer version

Add New Project Wizard

---

designer/components/buildozer_spec_editor.py
designer/components/designer_content.py
designer/components/playground.py
designer/core/project_manager.py
designer/tools/git_integration.py

Fixes #314 and all the issues with encoding failure.

Update all I/O operation to 'utf-8' encoding

---

designer/tools/bug_reporter.py

Change template design for issue of traceback to `code`. Helps in visibility of logs.
and change height of buttons to 70 from 50.

Bug Report Template

---

designer/app.py
designer/utils/constants.py

Fixes #270. Deletes created temporary directories on exit. Alternative PR to #289.

use temp directory for new projects

---

.travis.yml
README.md
designer/app.py
designer/components/dialogs/add_file.py
docs/source/installation.rst

Fixes #286 
Also, Update from Garden FileBrowser to XPopup to save and open project.

Save project to a folder
